- index.js
Hey,
What do you think about turning off block validation if validate is false? I use the lib as an emulation of the real network, so I need some flag to disable that validation.
> Turn off block validation if argument validate is false

- index.js
Fixes a race condition which caused Blockchain General State tests to break: https://github.com/ethereumjs/ethereumjs-blockchain/issues/28
> Make sure blockchain init is complete before adding blocks

- CHANGELOG.md
- package.json
Tightened dependencies to prevent the ``2.0.x`` version of the library to break
after ``ethereumjs`` Byzantium library updates
> [Pre-Byzantium Release] v2.0.2

- CHANGELOG.md
- package.json
Versioned Byzantium release, will be published on npm after merge.
Depends on: https://github.com/ethereumjs/ethereumjs-block/pull/37
See: https://github.com/ethereumjs/ethereumjs-vm/issues/209
> New release v2.1.0

- README.md
Updated README API documentation according to https://github.com/ethereumjs/ethereumjs-blockchain/pull/47 (Geth compatibility), added example code snippet.
> Updated API docs (Geth compatibility PR #47)

- README.md
- index.js
- test/index.js
- Added new methods to retrieve the latest header and full block
- Fixed a bug that prevented the latest header and block from being saved to the db
- Made some API doc changes to help clarify the difference between iterator heads and latest head/block. This hopefully helps explain the difference between the `getHead()`, `getLatestHeader()` and `getLatestBlock()` methods.
> Add getLatestHeader() and getLatestBlock() methods, fix saveHeads() bug and update API docs

- index.js
- test/index.js
This fixes a minor issue where the iterator, after calling the `run` function, doesn't pass along its error to the callback.
> Fix error propagation in iterator

- README.md
- index.js
- package.json
- test/index.js
- Added support for setting network and performing hardfork-specific validation by integrating with ethereumjs-common
- Added putHeader() and putHeaders() functions to provide header-chain functionality needed by ethereumjs-client
- Fixed a bug with caching
Addresses #54.  These changes are needed by ``ethereumjs-client`` (and also for block 2.x support in ``ethereumjs-vm``)
> Added support for setting network, hardfork-specific validation, putHeader()/putHeaders() functions

- index.js
- test/index.js
[Propagating errors](https://github.com/ethereumjs/ethereumjs-blockchain/pull/60) in `iterator` has caused an issue that I unfortunately hadn't foreseen. I'm sorry about this.
It tries to get the next blocks, and when the next block doesn't exist, it returns the `NotFoundError` upstream, which shouldn't be the case. I tried to fix this with minimal change , however please let me know if you want it fixed in another way.
Furthermore the PR modifies the test case checking for iterating an empty blockchain to check for errors in callback.
> Iterator should return without errors if no more blocks

- index.js
Fixes this issue with browserify: indutny/bn.js#147
> Fix: Replace toBuffer with toArrayLike

- README.md
- index.js
- package.json
- test/index.js
This PR updateds `levelup` to the latest version. The need for this update was discussed in this [issue](https://github.com/ethereumjs/ethereumjs-client/issues/53) for `ethereumjs-client` project.
I ran the tests and they are all passing. 
I ran the example code on my Geth DB, it seems to run OK.
> Updating levelup dependency

- index.js
This fixes an intermittent bug in `putBlock()` that is caused by `_saveHeads()` and `batchDbOps()` not being executed as part of the same db transaction. If `_saveHeads()` completes but `batchDbOps()` fails, it can lead to the head information being inconsistent with the actual head block.
> Fix putBlock() edge case

- index.js
[`new Buffer(string [, encoding])`](https://nodejs.org/api/buffer.html#buffer_new_buffer_string_encoding) is deprecated and this PR replaces the usages of it with [`Buffer.from(string [, encoding])`](https://nodejs.org/api/buffer.html#buffer_class_method_buffer_from_string_encoding). It's been deprecated since Node v6, which is the earliest version we run CI using.
> Replace uses of deprecated `new Buffer` with Buffer.from

- index.js
VM tests are [failing](https://github.com/ethereumjs/ethereumjs-vm/pull/412) on the `iterate` method of `Blockchain`. I think the reason is different versions of `levelup` being used in the two projects. VM passes its `db` to Blockchain, which checks the error by `err instanceof level.errors.NotFoundError` on a more recent version of `levelup`.
The modified condition seems to work, but it's probably a good idea to update `levelup` in VM as well.
> Fix levelup NotFoundError handling

- CHANGELOG.md
- README.md
- package.json
This also had the issue with added tests to the package, though absolutely not on the level like on the block library (just some 30-40 KB added).
I also hot-fixed the manually constructed documentation for the constructor a bit. This was a bit quick-and-dirty, nevertheless much needed and I would also like to postpone more to some separate PR with adding automated docs creation, Petersburg has priority right now.
Would be glad (again 😄) for some quick review. Thanks!
> New release v3.4.0

- .babelrc
- .travis.yml
- babel.config.js
- package.json
- src/dbManager.js
- src/index.js
- src/util.js
I started refactoring this by moving some of the (easier) db-related logic to a new class `DBManager` (which works with promises), and used `util.callbackify` in the same methods in `Blockchain`. I'm not sure if `util.callbackify` works in browser? (I think I remember browserify supports some libraries like `util`). But honestly, the bigger functions like `_putBlockOrHeader` are a piece of work, and I think rewriting it from scratch in typescript might be easier!
> Move some db ops to DBManager

- README.md
- docs/README.md
- docs/classes/blockchain.md
- docs/interfaces/blockchainoptions.md
- src/index.ts
This PR closes #101, #103 and #104.
#101: I couldn't figure out a way of describing the type of a parameter using tsdocs' tags. Instead, I created a `BlockchainOptions` type and documented it.
#103: Super straightforward.
#104: I checked that declared version of ethereumjs-common supports Petersburg. As it does, this change was super simple.
> Documentation updates

- docs/README.md
- docs/classes/blockchain.md
- docs/interfaces/blockchainoptions.md
- src/index.ts
- test/index.ts
I think we should use the occasion of a breaking release and get rid of the old DB constructor options. These have been deprecated by @vpulim along this major refactoring work https://github.com/ethereumjs/ethereumjs-blockchain/pull/47.
This PR removed both the ``opts.blockDb`` and ``opts.detailsDb`` options and the simplified no-opts-constructor directly passing in the DB (which adds very little benefit on the convenience level at the cost of higher complexity and eventually not very robust code).
> Remove deprecated db options

- package.json
- src/callbackify.ts
- src/index.ts
> Import callbackify

- src/index.ts
As we discussed in [this PR](https://github.com/ethereumjs/ethereumjs-vm/pull/566), having a clear interface for the `Blockchain` would be a good thing. 
This PR just adds it. I don't really like the name I chose (i.e. `BlockchainInterface`), but couldn't come up with a better one.
> Define a Blockchain interface

- src/index.ts
- test/index.ts
This PR closes #120 
I tried adding a test for this at the end of the huge `async.series` call, but I can't get it run. It's ignored by tape. Any idea?
> Granular validation

- package.json
- src/index.ts
This version of `ethereumjs-block` comes with the most recent `ethereumjs-tx` which has the Istanbul calldata fee reduction.
> Update ethereumjs-block to v2.2.1

- .nycrc
I forgot to add the code for `.nycrc` [from Holger's comment](https://github.com/ethereumjs/ethereumjs-blockchain/pull/134#issuecomment-560350726) to include calculating coverage from `dist`.
It's included in this PR - thanks Holger!
closes #139
> fix coverage by including dist

- CHANGELOG.md
- package.json
- test/index.ts
This PR updates the block and common dependencies and provides release notes for a `v4.0.3` release. 
The analysis/assignment of the failing tests to a potential bug in the `block` library was actually wrong. This was triggered because a MuirGlacier-containing PoW chain (Ropsten) block was compared to a non MuirGlacier chain (Rinkeby) block in the `block.canonicalDifficulty()` code, leading to the `>= MuirGlacier` comparison falsely evaluating to true for a non-HF initialized block. 
This could be fixed here by a slight update on the mismatched-chains test case by continuing to use different chains (to keep the tested case to be triggered) but switch to two PoW chains both containing the `MuirGlacier` fork.
> New release v4.0.3 (MuirGlacier), block and common updates
